// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJbEOxIWNo5Bd3ShnEPhezoWVf0X0JScI',
    appId: '1:620563571996:android:51eb7d4b260d286a2206d9',
    messagingSenderId: '620563571996',
    projectId: 'planmate-6a840',
    storageBucket: 'planmate-6a840.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdhGMyJo4XMRMD4zH-6YN-XkEQE7T16s8',
    appId: '1:620563571996:ios:321a3df4524f79272206d9',
    messagingSenderId: '620563571996',
    projectId: 'planmate-6a840',
    storageBucket: 'planmate-6a840.firebasestorage.app',
    androidClientId: '620563571996-jabtq7ui3rck3cj3cllgoso9s8qt1egm.apps.googleusercontent.com',
    iosClientId: '620563571996-87kv33i7bheug35qjav5r7u896ptuedu.apps.googleusercontent.com',
    iosBundleId: 'com.example.planMate',
  );

}